### ISSUE TITLE
broken system resolution

### ISSUE THREAD

**Issue by tardigrada123** [AlisterT/openjazz#74]
Hello I'm on Ubuntu 20.04 and built the binary simply with `make` (couldn't figure out how the autoconfig script is working - "./configure # --help lists options    make [install]" didn't work for me). Everything went fine but when I start the game in fullscreen mode with `./OpenJazz -f` the resolution of the system is scaled down to the one of the game even when i exit it. After a reboot the resolution is back to normal.
In the terminal there is this error: `X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x2c00003
  Serial number of failed request:  258
  Current serial number in output stream:  260`
I hope someone here can help,
thanks in advance

**Comment by tardigrada123** [comment]
OK, i searched a bit and found out that some raspberry users have a similiar problem playing another game - [https://www.raspberrypi.org/forums/viewtopic.php?t=249140](url) - someone stated that this problem occurs when the pc is connected to a tv rather than a standard computer monitor - this is also the case in my setup.
Anyway i found a workaround: first starting in window mode and then set the resolution. When I exit the game and start again in fullscreen mode the configuration stays and there  are no graphic problems.
So although this is a strange behavior and the workaround doesn't change the underlying problem, it is good enough for me...

**Comment by carstene1ns** [comment]
The problem here is that the default mode is very low resolution (320x200), which likely is not supported by the device/video driver.
SDL1.2 does some hacks to get a valid mode then (increasing until a valid mode is found and adding borders), but maybe the cleanup is bad then.

Can you give me the output of `xrandr -q`, so I can debug this better?

I think the best workaround for OJ is currently just using the closest mode above default. Ultimately this is solved when upgrading to SDL2, since desktop mode can be used then.

**Comment by tardigrada123** [comment]
Hello, here is the output of `xrandr -q` before the problem occurs: 
`xrandr -q `         
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 160mm x 90mm
   1920x1080     60.00*+  50.00    59.94    30.00    25.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.90  
   1280x960      60.00  
   1360x768      60.02  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
DP-3 disconnected (normal left inverted right x axis y axis)
HDMI-3 disconnected (normal left inverted right x axis y axis)

and after the problem occurs:
`xrandr -q ` 
Screen 0: minimum 320 x 200, current 640 x 480, maximum 16384 x 16384
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 connected primary 640x480+0+0 (normal left inverted right x axis y axis) 160mm x 90mm
   1920x1080     60.00 +  50.00    59.94    30.00    25.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.90  
   1280x960      60.00  
   1360x768      60.02  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00*   72.81    66.67    60.00    59.94  
   720x400       70.08  
DP-3 disconnected (normal left inverted right x axis y axis)
HDMI-3 disconnected (normal left inverted right x axis y axis)

I want to thank you and all the others working on this - it gives me some childhood memories back :-)
offtopic: In case anyone doesn't know this yet: there is a project for Jazz Jackrabbit 2: [https://github.com/fossabot/jazz2](url)

**Comment by carstene1ns** [comment]
It is indeed like I figured. The TV does not support the low resolution and falls back to 640x480.

**Comment by fabiangreffrath** [comment]
PrBoom has related code:
https://github.com/coelckers/prboom-plus/blob/24f1f117eca85726008ed50fa667c59814950acb/prboom2/src/SDL/i_video.c#L778

**Comment by carstene1ns** [comment]
@tardigrada123: I have made a work-in-progress commit in development branch: https://github.com/AlisterT/openjazz/commit/d3a5ea14a723ec164aa3a1f59bd6dc2460cde6f0
Can you try it out and report back, if it solves the initial issue? It should disallow setting an invalid resolution now.

@fabiangreffrath: Thanks for the pointer. Fortunately the user cannot set an invalid resolution through command line (yet), but once we add that, this code comes in handy.

**Comment by tardigrada123** [comment]
I've made a build from the development branch - the game starts fine in fullscreen mode but the system resolution is scaled down to 640x480 until I reboot.

**Comment by carstene1ns** [comment]
This shows another problem: The list of resolutions is hardcoded.
In your case setting an unsupported resolution crashes, normally SDL/X takes care of this for us, e.g. I just get letterboxing here.

The setup menu does not check if the resolution is valid after applying, so the game crashes. :/

**Comment by carstene1ns** [comment]
Made a new commit now that should fix this: https://github.com/AlisterT/openjazz/commit/c16c55c80c35d5adc4614e354db7c17acb37eac0.

About the broken screen resolution after close: this might be a driver issue or something within SDL/X.
This command should fix this without reboot: `xrandr --output HDMI-2 --auto`

**Comment by tardigrada123** [comment]
Sorry to say this but the Problem persists - the only change now is that I'm able to select higher resolution from the options menu, the game crashes right after applying the resolution (the situation before was that the game crashes when I try to select a higher resolution)

**Comment by carstene1ns** [comment]
While I believe now this is something I cannot fix, can you provide a backtrace?
Do a debug build, attach gdb and tell me where it crashes, maybe it is something obvious missing. :8ball:

**Comment by tardigrada123** [comment]
I made a debug build with `make CFLAGS=-g`  I hope this is correct
In the output file of GDB there was only this:
Could not open file: openjazz.cfg
Configuration file not found.
640x480 -> 1920x1080 

And here is the termial output (it crashed when i wanted to change the resolution in options menu):

gdb OpenJazz -f
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from OpenJazz...
(gdb) run > outfile.txt
Starting program: /home/lx/git/openjazz-development/OpenJazz > outfile.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6b3a700 (LWP 46831)]
[New Thread 0x7ffff1b50700 (LWP 46832)]
[Thread 0x7ffff1b50700 (LWP 46832) exited]
[New Thread 0x7ffff1b50700 (LWP 46839)]
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x773
  Serial number of failed request:  271
  Current serial number in output stream:  273
[Thread 0x7ffff6b3e040 (LWP 46825) exited]
[Thread 0x7ffff1b50700 (LWP 46839) exited]
[Inferior 1 (process 46825) exited with code 01]
(gdb) q

**Comment by carstene1ns** [comment]
I am closing this as something not fixable currently with legacy SDL.
